sudo: false
language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "5.0"
  - "6.0"

before_install:
  - travis_retry npm install -g npm@2.14.5
  - travis_retry npm install

script:
  - DEBUG=* npm test

notifications:
  email:
    - horacio.gonzalez@gmail.com
